


#
#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://shekharsaini:Lakh%21beer%401212@cluster0.o61o7.mongodb.net/journaldb?retryWrites=true&w=majority&appName=Cluster0
#      database: journaldb
#      auto-index-creation: true
#
#  application:
#    name: Journal
#  main:
#    allow-circular: true
#
#server:
#  port: 8081
#  servlet:
#    context-path: /journal


#spring.main.allow-circular-references=true



#spring.data.mongodb.username=localhost
#spring.data.mongodb.password=localhost

#Lakh!beer@1212
#Lakh%21beer%401212